name: ActionFramework Tests

on:
  push:
    branches:
      - main
    paths:
      - 'ActionFramework/**/*.swift'
  pull_request:
    paths:
      - 'ActionFramework/**/*.swift'

jobs:
  test:
    name: Run ActionFramework Tests
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Find Available Simulator and Run Tests
        run: |
          # iPhone 시뮬레이터 중 사용 가능한 첫 번째 기기 가져오기
          SIMULATOR_INFO=$(xcrun simctl list devices available | grep -m 1 "iPhone")
          SIMULATOR_UDID=$(echo "$SIMULATOR_INFO" | sed -E 's/.*\(([^)]+)\).*/\1/')

          echo "Using simulator with UDID: $SIMULATOR_UDID"
          
          # 시뮬레이터 부팅 (안 부팅해도 자동으로 부팅되긴 함, 그래도 명시적으로)
          xcrun simctl boot "$SIMULATOR_UDID" || true
          
          # 테스트 실행
          xcodebuild test \
            -workspace ActionTest.xcworkspace \
            -scheme ActionFramework \
            -destination "id=$SIMULATOR_UDID"