name: ActionFramework Tests

on:
  push:
    branches:
      - main
    paths:
      - 'ActionFramework/**/*.swift'
  pull_request:
    paths:
      - 'ActionFramework/**/*.swift'

jobs:
  test:
    name: Run ActionFramework Tests
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Find Available Simulator and Run Tests
        run: |
          # 첫 번째 사용 가능한 iPhone 시뮬레이터 UDID 추출 (JSON 파싱)
          UDID=$(xcrun simctl list devices --json | \
            jq -r '.devices | to_entries[] | select(.key | startswith("com.apple.CoreSimulator.SimRuntime.iOS")) |
              .value[] | select(.isAvailable == true and .name | test("^iPhone")) | .udid' | \
            head -n 1)

          echo "Using simulator with UDID: $UDID"

          # 시뮬레이터 부팅 (이미 부팅돼 있으면 무시)
          xcrun simctl boot "$UDID" || true

          # 테스트 실행
          xcodebuild test \
            -workspace ActionTest.xcworkspace \
            -scheme ActionFrameworkTests \
            -destination "id=$UDID"